/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CompleteQuest200ResponseDataGamification
import org.openapitools.client.models.CompleteQuest200ResponseDataTask

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param task 
 * @param gamification 
 */


data class CompleteQuest200ResponseData (

    @Json(name = "task")
    val task: CompleteQuest200ResponseDataTask? = null,

    @Json(name = "gamification")
    val gamification: CompleteQuest200ResponseDataGamification? = null

) {


}

