/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param theme 
 * @param propertyClass 
 */


data class CreateStoryFromTasksRequestUserPreferences (

    @Json(name = "theme")
    val theme: CreateStoryFromTasksRequestUserPreferences.Theme? = null,

    @Json(name = "class")
    val propertyClass: CreateStoryFromTasksRequestUserPreferences.PropertyClass? = null

) {

    /**
     * 
     *
     * Values: medieval,scifi,modern,fantasy
     */
    @JsonClass(generateAdapter = false)
    enum class Theme(val value: kotlin.String) {
        @Json(name = "medieval") medieval("medieval"),
        @Json(name = "scifi") scifi("scifi"),
        @Json(name = "modern") modern("modern"),
        @Json(name = "fantasy") fantasy("fantasy");
    }
    /**
     * 
     *
     * Values: Aventureiro,Guerreiro,Mago,Ladino,Paladino,Explorador
     */
    @JsonClass(generateAdapter = false)
    enum class PropertyClass(val value: kotlin.String) {
        @Json(name = "Aventureiro") Aventureiro("Aventureiro"),
        @Json(name = "Guerreiro") Guerreiro("Guerreiro"),
        @Json(name = "Mago") Mago("Mago"),
        @Json(name = "Ladino") Ladino("Ladino"),
        @Json(name = "Paladino") Paladino("Paladino"),
        @Json(name = "Explorador") Explorador("Explorador");
    }

}

