/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param title 
 * @param story 
 * @param theme 
 * @param totalXP 
 * @param estimatedPlayTime 
 */


data class CreateStoryFromTasks201ResponseDataStory (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "title")
    val title: kotlin.String? = null,

    @Json(name = "story")
    val story: kotlin.String? = null,

    @Json(name = "theme")
    val theme: kotlin.String? = null,

    @Json(name = "totalXP")
    val totalXP: java.math.BigDecimal? = null,

    @Json(name = "estimatedPlayTime")
    val estimatedPlayTime: kotlin.String? = null

) {


}

