/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.GetLeaderboard200ResponseDataLeaderboardInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param leaderboard 
 * @param period 
 * @param total 
 */


data class GetLeaderboard200ResponseData (

    @Json(name = "leaderboard")
    val leaderboard: kotlin.collections.List<GetLeaderboard200ResponseDataLeaderboardInner>? = null,

    @Json(name = "period")
    val period: kotlin.String? = null,

    @Json(name = "total")
    val total: java.math.BigDecimal? = null

) {


}

