/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param level 
 * @param totalXP 
 */


data class UserGamification (

    @Json(name = "level")
    val level: java.math.BigDecimal? = null,

    @Json(name = "totalXP")
    val totalXP: java.math.BigDecimal? = null

) {


}

