/*
 * Gamified Task Management API
 *
 * API REST gamificada para gerenciamento de tarefas com IA, XP, levels e sistema de recompensas
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GamifiedTasks.Client.Model;
using GamifiedTasks.Client.Client;
using System.Reflection;

namespace GamifiedTasks.Client.Test.Model
{
    /// <summary>
    ///  Class for testing GetAllUsers200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetAllUsers200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetAllUsers200Response
        //private GetAllUsers200Response instance;

        public GetAllUsers200ResponseTests()
        {
            // TODO uncomment below to create an instance of GetAllUsers200Response
            //instance = new GetAllUsers200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetAllUsers200Response
        /// </summary>
        [Fact]
        public void GetAllUsers200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetAllUsers200Response
            //Assert.IsType<GetAllUsers200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Fact]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
    }
}
