/*
 * Gamified Task Management API
 *
 * API REST gamificada para gerenciamento de tarefas com IA, XP, levels e sistema de recompensas
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GamifiedTasks.Client.Model;
using GamifiedTasks.Client.Client;
using System.Reflection;

namespace GamifiedTasks.Client.Test.Model
{
    /// <summary>
    ///  Class for testing GetUserStats200ResponseDataTasks
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetUserStats200ResponseDataTasksTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetUserStats200ResponseDataTasks
        //private GetUserStats200ResponseDataTasks instance;

        public GetUserStats200ResponseDataTasksTests()
        {
            // TODO uncomment below to create an instance of GetUserStats200ResponseDataTasks
            //instance = new GetUserStats200ResponseDataTasks();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetUserStats200ResponseDataTasks
        /// </summary>
        [Fact]
        public void GetUserStats200ResponseDataTasksInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetUserStats200ResponseDataTasks
            //Assert.IsType<GetUserStats200ResponseDataTasks>(instance);
        }

        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Fact]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }

        /// <summary>
        /// Test the property 'Completed'
        /// </summary>
        [Fact]
        public void CompletedTest()
        {
            // TODO unit test for the property 'Completed'
        }

        /// <summary>
        /// Test the property 'Pending'
        /// </summary>
        [Fact]
        public void PendingTest()
        {
            // TODO unit test for the property 'Pending'
        }

        /// <summary>
        /// Test the property 'InProgress'
        /// </summary>
        [Fact]
        public void InProgressTest()
        {
            // TODO unit test for the property 'InProgress'
        }

        /// <summary>
        /// Test the property 'Overdue'
        /// </summary>
        [Fact]
        public void OverdueTest()
        {
            // TODO unit test for the property 'Overdue'
        }
    }
}
