/*
 * Gamified Task Management API
 *
 * API REST gamificada para gerenciamento de tarefas com IA, XP, levels e sistema de recompensas
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GamifiedTasks.Client.Model;
using GamifiedTasks.Client.Client;
using System.Reflection;

namespace GamifiedTasks.Client.Test.Model
{
    /// <summary>
    ///  Class for testing GetUserStats200ResponseDataUsers
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetUserStats200ResponseDataUsersTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetUserStats200ResponseDataUsers
        //private GetUserStats200ResponseDataUsers instance;

        public GetUserStats200ResponseDataUsersTests()
        {
            // TODO uncomment below to create an instance of GetUserStats200ResponseDataUsers
            //instance = new GetUserStats200ResponseDataUsers();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetUserStats200ResponseDataUsers
        /// </summary>
        [Fact]
        public void GetUserStats200ResponseDataUsersInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetUserStats200ResponseDataUsers
            //Assert.IsType<GetUserStats200ResponseDataUsers>(instance);
        }

        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Fact]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }

        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Fact]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }

        /// <summary>
        /// Test the property 'Inactive'
        /// </summary>
        [Fact]
        public void InactiveTest()
        {
            // TODO unit test for the property 'Inactive'
        }

        /// <summary>
        /// Test the property 'Admins'
        /// </summary>
        [Fact]
        public void AdminsTest()
        {
            // TODO unit test for the property 'Admins'
        }
    }
}
