/*
 * Gamified Task Management API
 *
 * API REST gamificada para gerenciamento de tarefas com IA, XP, levels e sistema de recompensas
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GamifiedTasks.Client.Model;
using GamifiedTasks.Client.Client;
using System.Reflection;

namespace GamifiedTasks.Client.Test.Model
{
    /// <summary>
    ///  Class for testing ListTasks200ResponseData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListTasks200ResponseDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListTasks200ResponseData
        //private ListTasks200ResponseData instance;

        public ListTasks200ResponseDataTests()
        {
            // TODO uncomment below to create an instance of ListTasks200ResponseData
            //instance = new ListTasks200ResponseData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListTasks200ResponseData
        /// </summary>
        [Fact]
        public void ListTasks200ResponseDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListTasks200ResponseData
            //Assert.IsType<ListTasks200ResponseData>(instance);
        }

        /// <summary>
        /// Test the property 'Tasks'
        /// </summary>
        [Fact]
        public void TasksTest()
        {
            // TODO unit test for the property 'Tasks'
        }

        /// <summary>
        /// Test the property 'Pagination'
        /// </summary>
        [Fact]
        public void PaginationTest()
        {
            // TODO unit test for the property 'Pagination'
        }
    }
}
