/*
 * Gamified Task Management API
 *
 * API REST gamificada para gerenciamento de tarefas com IA, XP, levels e sistema de recompensas
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetGlobalStats200ResponseData {
    #[serde(rename = "users", skip_serializing_if = "Option::is_none")]
    pub users: Option<Box<models::GetGlobalStats200ResponseDataUsers>>,
    #[serde(rename = "gamification", skip_serializing_if = "Option::is_none")]
    pub gamification: Option<Box<models::GetGlobalStats200ResponseDataGamification>>,
    #[serde(rename = "stories", skip_serializing_if = "Option::is_none")]
    pub stories: Option<Box<models::GetGlobalStats200ResponseDataStories>>,
}

impl GetGlobalStats200ResponseData {
    pub fn new() -> GetGlobalStats200ResponseData {
        GetGlobalStats200ResponseData {
            users: None,
            gamification: None,
            stories: None,
        }
    }
}

