/*
 * Gamified Task Management API
 *
 * API REST gamificada para gerenciamento de tarefas com IA, XP, levels e sistema de recompensas
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetBadges200ResponseDataEarnedInner {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "icon", skip_serializing_if = "Option::is_none")]
    pub icon: Option<String>,
    #[serde(rename = "earned", skip_serializing_if = "Option::is_none")]
    pub earned: Option<bool>,
}

impl GetBadges200ResponseDataEarnedInner {
    pub fn new() -> GetBadges200ResponseDataEarnedInner {
        GetBadges200ResponseDataEarnedInner {
            id: None,
            name: None,
            description: None,
            icon: None,
            earned: None,
        }
    }
}

