/*
 * Gamified Task Management API
 *
 * API REST gamificada para gerenciamento de tarefas com IA, XP, levels e sistema de recompensas
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetGlobalStats200ResponseDataUsers {
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<f64>,
    #[serde(rename = "averageLevel", skip_serializing_if = "Option::is_none")]
    pub average_level: Option<f64>,
}

impl GetGlobalStats200ResponseDataUsers {
    pub fn new() -> GetGlobalStats200ResponseDataUsers {
        GetGlobalStats200ResponseDataUsers {
            total: None,
            average_level: None,
        }
    }
}

