/*
Gamified Task Management API

API REST gamificada para gerenciamento de tarefas com IA, XP, levels e sistema de recompensas

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CompleteQuestRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CompleteQuestRequest{}

// CompleteQuestRequest struct for CompleteQuestRequest
type CompleteQuestRequest struct {
	// Tempo gasto em minutos
	CompletionTime *float32 `json:"completionTime,omitempty"`
}

// NewCompleteQuestRequest instantiates a new CompleteQuestRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCompleteQuestRequest() *CompleteQuestRequest {
	this := CompleteQuestRequest{}
	return &this
}

// NewCompleteQuestRequestWithDefaults instantiates a new CompleteQuestRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCompleteQuestRequestWithDefaults() *CompleteQuestRequest {
	this := CompleteQuestRequest{}
	return &this
}

// GetCompletionTime returns the CompletionTime field value if set, zero value otherwise.
func (o *CompleteQuestRequest) GetCompletionTime() float32 {
	if o == nil || IsNil(o.CompletionTime) {
		var ret float32
		return ret
	}
	return *o.CompletionTime
}

// GetCompletionTimeOk returns a tuple with the CompletionTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompleteQuestRequest) GetCompletionTimeOk() (*float32, bool) {
	if o == nil || IsNil(o.CompletionTime) {
		return nil, false
	}
	return o.CompletionTime, true
}

// HasCompletionTime returns a boolean if a field has been set.
func (o *CompleteQuestRequest) HasCompletionTime() bool {
	if o != nil && !IsNil(o.CompletionTime) {
		return true
	}

	return false
}

// SetCompletionTime gets a reference to the given float32 and assigns it to the CompletionTime field.
func (o *CompleteQuestRequest) SetCompletionTime(v float32) {
	o.CompletionTime = &v
}

func (o CompleteQuestRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CompleteQuestRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CompletionTime) {
		toSerialize["completionTime"] = o.CompletionTime
	}
	return toSerialize, nil
}

type NullableCompleteQuestRequest struct {
	value *CompleteQuestRequest
	isSet bool
}

func (v NullableCompleteQuestRequest) Get() *CompleteQuestRequest {
	return v.value
}

func (v *NullableCompleteQuestRequest) Set(val *CompleteQuestRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCompleteQuestRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCompleteQuestRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCompleteQuestRequest(val *CompleteQuestRequest) *NullableCompleteQuestRequest {
	return &NullableCompleteQuestRequest{value: val, isSet: true}
}

func (v NullableCompleteQuestRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCompleteQuestRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


