/*
Gamified Task Management API

API REST gamificada para gerenciamento de tarefas com IA, XP, levels e sistema de recompensas

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UpdateGamificationPreferencesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateGamificationPreferencesRequest{}

// UpdateGamificationPreferencesRequest struct for UpdateGamificationPreferencesRequest
type UpdateGamificationPreferencesRequest struct {
	Class *string `json:"class,omitempty"`
	Theme *string `json:"theme,omitempty"`
	AutoShare *bool `json:"autoShare,omitempty"`
	ShareOnLevelUp *bool `json:"shareOnLevelUp,omitempty"`
	ShareOnBadge *bool `json:"shareOnBadge,omitempty"`
}

// NewUpdateGamificationPreferencesRequest instantiates a new UpdateGamificationPreferencesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateGamificationPreferencesRequest() *UpdateGamificationPreferencesRequest {
	this := UpdateGamificationPreferencesRequest{}
	return &this
}

// NewUpdateGamificationPreferencesRequestWithDefaults instantiates a new UpdateGamificationPreferencesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateGamificationPreferencesRequestWithDefaults() *UpdateGamificationPreferencesRequest {
	this := UpdateGamificationPreferencesRequest{}
	return &this
}

// GetClass returns the Class field value if set, zero value otherwise.
func (o *UpdateGamificationPreferencesRequest) GetClass() string {
	if o == nil || IsNil(o.Class) {
		var ret string
		return ret
	}
	return *o.Class
}

// GetClassOk returns a tuple with the Class field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateGamificationPreferencesRequest) GetClassOk() (*string, bool) {
	if o == nil || IsNil(o.Class) {
		return nil, false
	}
	return o.Class, true
}

// HasClass returns a boolean if a field has been set.
func (o *UpdateGamificationPreferencesRequest) HasClass() bool {
	if o != nil && !IsNil(o.Class) {
		return true
	}

	return false
}

// SetClass gets a reference to the given string and assigns it to the Class field.
func (o *UpdateGamificationPreferencesRequest) SetClass(v string) {
	o.Class = &v
}

// GetTheme returns the Theme field value if set, zero value otherwise.
func (o *UpdateGamificationPreferencesRequest) GetTheme() string {
	if o == nil || IsNil(o.Theme) {
		var ret string
		return ret
	}
	return *o.Theme
}

// GetThemeOk returns a tuple with the Theme field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateGamificationPreferencesRequest) GetThemeOk() (*string, bool) {
	if o == nil || IsNil(o.Theme) {
		return nil, false
	}
	return o.Theme, true
}

// HasTheme returns a boolean if a field has been set.
func (o *UpdateGamificationPreferencesRequest) HasTheme() bool {
	if o != nil && !IsNil(o.Theme) {
		return true
	}

	return false
}

// SetTheme gets a reference to the given string and assigns it to the Theme field.
func (o *UpdateGamificationPreferencesRequest) SetTheme(v string) {
	o.Theme = &v
}

// GetAutoShare returns the AutoShare field value if set, zero value otherwise.
func (o *UpdateGamificationPreferencesRequest) GetAutoShare() bool {
	if o == nil || IsNil(o.AutoShare) {
		var ret bool
		return ret
	}
	return *o.AutoShare
}

// GetAutoShareOk returns a tuple with the AutoShare field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateGamificationPreferencesRequest) GetAutoShareOk() (*bool, bool) {
	if o == nil || IsNil(o.AutoShare) {
		return nil, false
	}
	return o.AutoShare, true
}

// HasAutoShare returns a boolean if a field has been set.
func (o *UpdateGamificationPreferencesRequest) HasAutoShare() bool {
	if o != nil && !IsNil(o.AutoShare) {
		return true
	}

	return false
}

// SetAutoShare gets a reference to the given bool and assigns it to the AutoShare field.
func (o *UpdateGamificationPreferencesRequest) SetAutoShare(v bool) {
	o.AutoShare = &v
}

// GetShareOnLevelUp returns the ShareOnLevelUp field value if set, zero value otherwise.
func (o *UpdateGamificationPreferencesRequest) GetShareOnLevelUp() bool {
	if o == nil || IsNil(o.ShareOnLevelUp) {
		var ret bool
		return ret
	}
	return *o.ShareOnLevelUp
}

// GetShareOnLevelUpOk returns a tuple with the ShareOnLevelUp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateGamificationPreferencesRequest) GetShareOnLevelUpOk() (*bool, bool) {
	if o == nil || IsNil(o.ShareOnLevelUp) {
		return nil, false
	}
	return o.ShareOnLevelUp, true
}

// HasShareOnLevelUp returns a boolean if a field has been set.
func (o *UpdateGamificationPreferencesRequest) HasShareOnLevelUp() bool {
	if o != nil && !IsNil(o.ShareOnLevelUp) {
		return true
	}

	return false
}

// SetShareOnLevelUp gets a reference to the given bool and assigns it to the ShareOnLevelUp field.
func (o *UpdateGamificationPreferencesRequest) SetShareOnLevelUp(v bool) {
	o.ShareOnLevelUp = &v
}

// GetShareOnBadge returns the ShareOnBadge field value if set, zero value otherwise.
func (o *UpdateGamificationPreferencesRequest) GetShareOnBadge() bool {
	if o == nil || IsNil(o.ShareOnBadge) {
		var ret bool
		return ret
	}
	return *o.ShareOnBadge
}

// GetShareOnBadgeOk returns a tuple with the ShareOnBadge field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateGamificationPreferencesRequest) GetShareOnBadgeOk() (*bool, bool) {
	if o == nil || IsNil(o.ShareOnBadge) {
		return nil, false
	}
	return o.ShareOnBadge, true
}

// HasShareOnBadge returns a boolean if a field has been set.
func (o *UpdateGamificationPreferencesRequest) HasShareOnBadge() bool {
	if o != nil && !IsNil(o.ShareOnBadge) {
		return true
	}

	return false
}

// SetShareOnBadge gets a reference to the given bool and assigns it to the ShareOnBadge field.
func (o *UpdateGamificationPreferencesRequest) SetShareOnBadge(v bool) {
	o.ShareOnBadge = &v
}

func (o UpdateGamificationPreferencesRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateGamificationPreferencesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Class) {
		toSerialize["class"] = o.Class
	}
	if !IsNil(o.Theme) {
		toSerialize["theme"] = o.Theme
	}
	if !IsNil(o.AutoShare) {
		toSerialize["autoShare"] = o.AutoShare
	}
	if !IsNil(o.ShareOnLevelUp) {
		toSerialize["shareOnLevelUp"] = o.ShareOnLevelUp
	}
	if !IsNil(o.ShareOnBadge) {
		toSerialize["shareOnBadge"] = o.ShareOnBadge
	}
	return toSerialize, nil
}

type NullableUpdateGamificationPreferencesRequest struct {
	value *UpdateGamificationPreferencesRequest
	isSet bool
}

func (v NullableUpdateGamificationPreferencesRequest) Get() *UpdateGamificationPreferencesRequest {
	return v.value
}

func (v *NullableUpdateGamificationPreferencesRequest) Set(val *UpdateGamificationPreferencesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateGamificationPreferencesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateGamificationPreferencesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateGamificationPreferencesRequest(val *UpdateGamificationPreferencesRequest) *NullableUpdateGamificationPreferencesRequest {
	return &NullableUpdateGamificationPreferencesRequest{value: val, isSet: true}
}

func (v NullableUpdateGamificationPreferencesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateGamificationPreferencesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


