/*
Gamified Task Management API

API REST gamificada para gerenciamento de tarefas com IA, XP, levels e sistema de recompensas

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiUsersStatsGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiUsersStatsGet200Response{}

// ApiUsersStatsGet200Response struct for ApiUsersStatsGet200Response
type ApiUsersStatsGet200Response struct {
	Success *bool `json:"success,omitempty"`
	Data *ApiUsersStatsGet200ResponseData `json:"data,omitempty"`
}

// NewApiUsersStatsGet200Response instantiates a new ApiUsersStatsGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiUsersStatsGet200Response() *ApiUsersStatsGet200Response {
	this := ApiUsersStatsGet200Response{}
	return &this
}

// NewApiUsersStatsGet200ResponseWithDefaults instantiates a new ApiUsersStatsGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiUsersStatsGet200ResponseWithDefaults() *ApiUsersStatsGet200Response {
	this := ApiUsersStatsGet200Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *ApiUsersStatsGet200Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiUsersStatsGet200Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *ApiUsersStatsGet200Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *ApiUsersStatsGet200Response) SetSuccess(v bool) {
	o.Success = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ApiUsersStatsGet200Response) GetData() ApiUsersStatsGet200ResponseData {
	if o == nil || IsNil(o.Data) {
		var ret ApiUsersStatsGet200ResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiUsersStatsGet200Response) GetDataOk() (*ApiUsersStatsGet200ResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ApiUsersStatsGet200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given ApiUsersStatsGet200ResponseData and assigns it to the Data field.
func (o *ApiUsersStatsGet200Response) SetData(v ApiUsersStatsGet200ResponseData) {
	o.Data = &v
}

func (o ApiUsersStatsGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiUsersStatsGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableApiUsersStatsGet200Response struct {
	value *ApiUsersStatsGet200Response
	isSet bool
}

func (v NullableApiUsersStatsGet200Response) Get() *ApiUsersStatsGet200Response {
	return v.value
}

func (v *NullableApiUsersStatsGet200Response) Set(val *ApiUsersStatsGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiUsersStatsGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiUsersStatsGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiUsersStatsGet200Response(val *ApiUsersStatsGet200Response) *NullableApiUsersStatsGet200Response {
	return &NullableApiUsersStatsGet200Response{value: val, isSet: true}
}

func (v NullableApiUsersStatsGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiUsersStatsGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


