/*
Gamified Task Management API

API REST gamificada para gerenciamento de tarefas com IA, XP, levels e sistema de recompensas

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiUsersGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiUsersGet200Response{}

// ApiUsersGet200Response struct for ApiUsersGet200Response
type ApiUsersGet200Response struct {
	Success *bool `json:"success,omitempty"`
	Data *ApiUsersGet200ResponseData `json:"data,omitempty"`
}

// NewApiUsersGet200Response instantiates a new ApiUsersGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiUsersGet200Response() *ApiUsersGet200Response {
	this := ApiUsersGet200Response{}
	return &this
}

// NewApiUsersGet200ResponseWithDefaults instantiates a new ApiUsersGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiUsersGet200ResponseWithDefaults() *ApiUsersGet200Response {
	this := ApiUsersGet200Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *ApiUsersGet200Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiUsersGet200Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *ApiUsersGet200Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *ApiUsersGet200Response) SetSuccess(v bool) {
	o.Success = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ApiUsersGet200Response) GetData() ApiUsersGet200ResponseData {
	if o == nil || IsNil(o.Data) {
		var ret ApiUsersGet200ResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiUsersGet200Response) GetDataOk() (*ApiUsersGet200ResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ApiUsersGet200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given ApiUsersGet200ResponseData and assigns it to the Data field.
func (o *ApiUsersGet200Response) SetData(v ApiUsersGet200ResponseData) {
	o.Data = &v
}

func (o ApiUsersGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiUsersGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableApiUsersGet200Response struct {
	value *ApiUsersGet200Response
	isSet bool
}

func (v NullableApiUsersGet200Response) Get() *ApiUsersGet200Response {
	return v.value
}

func (v *NullableApiUsersGet200Response) Set(val *ApiUsersGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiUsersGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiUsersGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiUsersGet200Response(val *ApiUsersGet200Response) *NullableApiUsersGet200Response {
	return &NullableApiUsersGet200Response{value: val, isSet: true}
}

func (v NullableApiUsersGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiUsersGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


