/*
Gamified Task Management API

API REST gamificada para gerenciamento de tarefas com IA, XP, levels e sistema de recompensas

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiAuthLoginPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiAuthLoginPostRequest{}

// ApiAuthLoginPostRequest struct for ApiAuthLoginPostRequest
type ApiAuthLoginPostRequest struct {
	Email string `json:"email"`
	Password string `json:"password"`
}

type _ApiAuthLoginPostRequest ApiAuthLoginPostRequest

// NewApiAuthLoginPostRequest instantiates a new ApiAuthLoginPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiAuthLoginPostRequest(email string, password string) *ApiAuthLoginPostRequest {
	this := ApiAuthLoginPostRequest{}
	this.Email = email
	this.Password = password
	return &this
}

// NewApiAuthLoginPostRequestWithDefaults instantiates a new ApiAuthLoginPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiAuthLoginPostRequestWithDefaults() *ApiAuthLoginPostRequest {
	this := ApiAuthLoginPostRequest{}
	return &this
}

// GetEmail returns the Email field value
func (o *ApiAuthLoginPostRequest) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *ApiAuthLoginPostRequest) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *ApiAuthLoginPostRequest) SetEmail(v string) {
	o.Email = v
}

// GetPassword returns the Password field value
func (o *ApiAuthLoginPostRequest) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *ApiAuthLoginPostRequest) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *ApiAuthLoginPostRequest) SetPassword(v string) {
	o.Password = v
}

func (o ApiAuthLoginPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiAuthLoginPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	toSerialize["password"] = o.Password
	return toSerialize, nil
}

func (o *ApiAuthLoginPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
		"password",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiAuthLoginPostRequest := _ApiAuthLoginPostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiAuthLoginPostRequest)

	if err != nil {
		return err
	}

	*o = ApiAuthLoginPostRequest(varApiAuthLoginPostRequest)

	return err
}

type NullableApiAuthLoginPostRequest struct {
	value *ApiAuthLoginPostRequest
	isSet bool
}

func (v NullableApiAuthLoginPostRequest) Get() *ApiAuthLoginPostRequest {
	return v.value
}

func (v *NullableApiAuthLoginPostRequest) Set(val *ApiAuthLoginPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiAuthLoginPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiAuthLoginPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiAuthLoginPostRequest(val *ApiAuthLoginPostRequest) *NullableApiAuthLoginPostRequest {
	return &NullableApiAuthLoginPostRequest{value: val, isSet: true}
}

func (v NullableApiAuthLoginPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiAuthLoginPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


