/*
 * Gamified Task Management API
 *
 * API REST gamificada para gerenciamento de tarefas com IA, XP, levels e sistema de recompensas
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using GamifiedTasks.Client.Api;
using GamifiedTasks.Client.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace GamifiedTasks.Client.Test.Api
{
    /// <summary>
    ///  Class for testing UsersApi
    /// </summary>
    public sealed class UsersApiTests : ApiTestsBase
    {
        private readonly IUsersApi _instance;

        public UsersApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IUsersApi>();
        }

        /// <summary>
        /// Test DeleteUser
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task DeleteUserAsyncTest()
        {
            string id = default!;
            var response = await _instance.DeleteUserAsync(id);
            var model = response.Ok();
            Assert.IsType<DeleteUser200Response>(model);
        }

        /// <summary>
        /// Test GetAllUsers
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetAllUsersAsyncTest()
        {
            Client.Option<int> page = default!;
            Client.Option<int> limit = default!;
            Client.Option<string> search = default!;
            Client.Option<string> role = default!;
            Client.Option<bool> isActive = default!;
            var response = await _instance.GetAllUsersAsync(page, limit, search, role, isActive);
            var model = response.Ok();
            Assert.IsType<GetAllUsers200Response>(model);
        }

        /// <summary>
        /// Test GetUserById
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetUserByIdAsyncTest()
        {
            string id = default!;
            var response = await _instance.GetUserByIdAsync(id);
            var model = response.Ok();
            Assert.IsType<GetUserById200Response>(model);
        }

        /// <summary>
        /// Test GetUserStats
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetUserStatsAsyncTest()
        {
            var response = await _instance.GetUserStatsAsync();
            var model = response.Ok();
            Assert.IsType<GetUserStats200Response>(model);
        }

        /// <summary>
        /// Test ToggleUserStatus
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ToggleUserStatusAsyncTest()
        {
            string id = default!;
            var response = await _instance.ToggleUserStatusAsync(id);
            var model = response.Ok();
            Assert.IsType<ToggleUserStatus200Response>(model);
        }

        /// <summary>
        /// Test UpdateUser
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task UpdateUserAsyncTest()
        {
            string id = default!;
            UpdateUserRequest updateUserRequest = default!;
            var response = await _instance.UpdateUserAsync(id, updateUserRequest);
            var model = response.Ok();
            Assert.IsType<UpdateUser200Response>(model);
        }
    }
}
