/*
 * Gamified Task Management API
 * API REST gamificada para gerenciamento de tarefas com IA, XP, levels e sistema de recompensas
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.ApiGamificationGlobalStatsGet200ResponseDataGamification;
import org.openapitools.client.model.ApiGamificationGlobalStatsGet200ResponseDataStories;
import org.openapitools.client.model.ApiGamificationGlobalStatsGet200ResponseDataUsers;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ApiGamificationGlobalStatsGet200ResponseData
 */
public class ApiGamificationGlobalStatsGet200ResponseDataTest {
    private final ApiGamificationGlobalStatsGet200ResponseData model = new ApiGamificationGlobalStatsGet200ResponseData();

    /**
     * Model tests for ApiGamificationGlobalStatsGet200ResponseData
     */
    @Test
    public void testApiGamificationGlobalStatsGet200ResponseData() {
        // TODO: test ApiGamificationGlobalStatsGet200ResponseData
    }

    /**
     * Test the property 'users'
     */
    @Test
    public void usersTest() {
        // TODO: test users
    }

    /**
     * Test the property 'gamification'
     */
    @Test
    public void gamificationTest() {
        // TODO: test gamification
    }

    /**
     * Test the property 'stories'
     */
    @Test
    public void storiesTest() {
        // TODO: test stories
    }

}
