/*
 * Gamified Task Management API
 * API REST gamificada para gerenciamento de tarefas com IA, XP, levels e sistema de recompensas
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ApiGamificationBadgesGet200ResponseDataEarnedInner
 */
public class ApiGamificationBadgesGet200ResponseDataEarnedInnerTest {
    private final ApiGamificationBadgesGet200ResponseDataEarnedInner model = new ApiGamificationBadgesGet200ResponseDataEarnedInner();

    /**
     * Model tests for ApiGamificationBadgesGet200ResponseDataEarnedInner
     */
    @Test
    public void testApiGamificationBadgesGet200ResponseDataEarnedInner() {
        // TODO: test ApiGamificationBadgesGet200ResponseDataEarnedInner
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'icon'
     */
    @Test
    public void iconTest() {
        // TODO: test icon
    }

    /**
     * Test the property 'earned'
     */
    @Test
    public void earnedTest() {
        // TODO: test earned
    }

}
