/*
 * Gamified Task Management API
 * API REST gamificada para gerenciamento de tarefas com IA, XP, levels e sistema de recompensas
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ApiTasksStatsGet200ResponseDataStats
 */
public class ApiTasksStatsGet200ResponseDataStatsTest {
    private final ApiTasksStatsGet200ResponseDataStats model = new ApiTasksStatsGet200ResponseDataStats();

    /**
     * Model tests for ApiTasksStatsGet200ResponseDataStats
     */
    @Test
    public void testApiTasksStatsGet200ResponseDataStats() {
        // TODO: test ApiTasksStatsGet200ResponseDataStats
    }

    /**
     * Test the property 'total'
     */
    @Test
    public void totalTest() {
        // TODO: test total
    }

    /**
     * Test the property 'pending'
     */
    @Test
    public void pendingTest() {
        // TODO: test pending
    }

    /**
     * Test the property 'inProgress'
     */
    @Test
    public void inProgressTest() {
        // TODO: test inProgress
    }

    /**
     * Test the property 'completed'
     */
    @Test
    public void completedTest() {
        // TODO: test completed
    }

    /**
     * Test the property 'overdue'
     */
    @Test
    public void overdueTest() {
        // TODO: test overdue
    }

    /**
     * Test the property 'completedThisMonth'
     */
    @Test
    public void completedThisMonthTest() {
        // TODO: test completedThisMonth
    }

}
