/*
 * Gamified Task Management API
 * API REST gamificada para gerenciamento de tarefas com IA, XP, levels e sistema de recompensas
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ApiTasksStoryPost201ResponseDataStory
 */
public class ApiTasksStoryPost201ResponseDataStoryTest {
    private final ApiTasksStoryPost201ResponseDataStory model = new ApiTasksStoryPost201ResponseDataStory();

    /**
     * Model tests for ApiTasksStoryPost201ResponseDataStory
     */
    @Test
    public void testApiTasksStoryPost201ResponseDataStory() {
        // TODO: test ApiTasksStoryPost201ResponseDataStory
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'story'
     */
    @Test
    public void storyTest() {
        // TODO: test story
    }

    /**
     * Test the property 'theme'
     */
    @Test
    public void themeTest() {
        // TODO: test theme
    }

    /**
     * Test the property 'totalXP'
     */
    @Test
    public void totalXPTest() {
        // TODO: test totalXP
    }

    /**
     * Test the property 'estimatedPlayTime'
     */
    @Test
    public void estimatedPlayTimeTest() {
        // TODO: test estimatedPlayTime
    }

}
