/*
 * Gamified Task Management API
 * API REST gamificada para gerenciamento de tarefas com IA, XP, levels e sistema de recompensas
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.GetAllUsers200ResponseDataPagination;
import org.openapitools.client.model.User;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetAllUsers200ResponseData
 */
public class GetAllUsers200ResponseDataTest {
    private final GetAllUsers200ResponseData model = new GetAllUsers200ResponseData();

    /**
     * Model tests for GetAllUsers200ResponseData
     */
    @Test
    public void testGetAllUsers200ResponseData() {
        // TODO: test GetAllUsers200ResponseData
    }

    /**
     * Test the property 'users'
     */
    @Test
    public void usersTest() {
        // TODO: test users
    }

    /**
     * Test the property 'pagination'
     */
    @Test
    public void paginationTest() {
        // TODO: test pagination
    }

}
