/*
 * Gamified Task Management API
 * API REST gamificada para gerenciamento de tarefas com IA, XP, levels e sistema de recompensas
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * GetGamificationDashboard200ResponseDataStats
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-06-14T22:52:12.042322500-03:00[America/Sao_Paulo]", comments = "Generator version: 7.13.0")
public class GetGamificationDashboard200ResponseDataStats {
  public static final String SERIALIZED_NAME_LEVEL = "level";
  @SerializedName(SERIALIZED_NAME_LEVEL)
  @javax.annotation.Nullable
  private BigDecimal level;

  public static final String SERIALIZED_NAME_TOTAL_X_P = "totalXP";
  @SerializedName(SERIALIZED_NAME_TOTAL_X_P)
  @javax.annotation.Nullable
  private BigDecimal totalXP;

  public static final String SERIALIZED_NAME_TASKS_COMPLETED = "tasksCompleted";
  @SerializedName(SERIALIZED_NAME_TASKS_COMPLETED)
  @javax.annotation.Nullable
  private BigDecimal tasksCompleted;

  public static final String SERIALIZED_NAME_CURRENT_STREAK = "currentStreak";
  @SerializedName(SERIALIZED_NAME_CURRENT_STREAK)
  @javax.annotation.Nullable
  private BigDecimal currentStreak;

  public static final String SERIALIZED_NAME_LONGEST_STREAK = "longestStreak";
  @SerializedName(SERIALIZED_NAME_LONGEST_STREAK)
  @javax.annotation.Nullable
  private BigDecimal longestStreak;

  public static final String SERIALIZED_NAME_BADGES = "badges";
  @SerializedName(SERIALIZED_NAME_BADGES)
  @javax.annotation.Nullable
  private List<String> badges = new ArrayList<>();

  public static final String SERIALIZED_NAME_NEXT_LEVEL = "nextLevel";
  @SerializedName(SERIALIZED_NAME_NEXT_LEVEL)
  @javax.annotation.Nullable
  private Object nextLevel;

  public GetGamificationDashboard200ResponseDataStats() {
  }

  public GetGamificationDashboard200ResponseDataStats level(@javax.annotation.Nullable BigDecimal level) {
    this.level = level;
    return this;
  }

  /**
   * Get level
   * @return level
   */
  @javax.annotation.Nullable
  public BigDecimal getLevel() {
    return level;
  }

  public void setLevel(@javax.annotation.Nullable BigDecimal level) {
    this.level = level;
  }


  public GetGamificationDashboard200ResponseDataStats totalXP(@javax.annotation.Nullable BigDecimal totalXP) {
    this.totalXP = totalXP;
    return this;
  }

  /**
   * Get totalXP
   * @return totalXP
   */
  @javax.annotation.Nullable
  public BigDecimal getTotalXP() {
    return totalXP;
  }

  public void setTotalXP(@javax.annotation.Nullable BigDecimal totalXP) {
    this.totalXP = totalXP;
  }


  public GetGamificationDashboard200ResponseDataStats tasksCompleted(@javax.annotation.Nullable BigDecimal tasksCompleted) {
    this.tasksCompleted = tasksCompleted;
    return this;
  }

  /**
   * Get tasksCompleted
   * @return tasksCompleted
   */
  @javax.annotation.Nullable
  public BigDecimal getTasksCompleted() {
    return tasksCompleted;
  }

  public void setTasksCompleted(@javax.annotation.Nullable BigDecimal tasksCompleted) {
    this.tasksCompleted = tasksCompleted;
  }


  public GetGamificationDashboard200ResponseDataStats currentStreak(@javax.annotation.Nullable BigDecimal currentStreak) {
    this.currentStreak = currentStreak;
    return this;
  }

  /**
   * Get currentStreak
   * @return currentStreak
   */
  @javax.annotation.Nullable
  public BigDecimal getCurrentStreak() {
    return currentStreak;
  }

  public void setCurrentStreak(@javax.annotation.Nullable BigDecimal currentStreak) {
    this.currentStreak = currentStreak;
  }


  public GetGamificationDashboard200ResponseDataStats longestStreak(@javax.annotation.Nullable BigDecimal longestStreak) {
    this.longestStreak = longestStreak;
    return this;
  }

  /**
   * Get longestStreak
   * @return longestStreak
   */
  @javax.annotation.Nullable
  public BigDecimal getLongestStreak() {
    return longestStreak;
  }

  public void setLongestStreak(@javax.annotation.Nullable BigDecimal longestStreak) {
    this.longestStreak = longestStreak;
  }


  public GetGamificationDashboard200ResponseDataStats badges(@javax.annotation.Nullable List<String> badges) {
    this.badges = badges;
    return this;
  }

  public GetGamificationDashboard200ResponseDataStats addBadgesItem(String badgesItem) {
    if (this.badges == null) {
      this.badges = new ArrayList<>();
    }
    this.badges.add(badgesItem);
    return this;
  }

  /**
   * Get badges
   * @return badges
   */
  @javax.annotation.Nullable
  public List<String> getBadges() {
    return badges;
  }

  public void setBadges(@javax.annotation.Nullable List<String> badges) {
    this.badges = badges;
  }


  public GetGamificationDashboard200ResponseDataStats nextLevel(@javax.annotation.Nullable Object nextLevel) {
    this.nextLevel = nextLevel;
    return this;
  }

  /**
   * Get nextLevel
   * @return nextLevel
   */
  @javax.annotation.Nullable
  public Object getNextLevel() {
    return nextLevel;
  }

  public void setNextLevel(@javax.annotation.Nullable Object nextLevel) {
    this.nextLevel = nextLevel;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetGamificationDashboard200ResponseDataStats getGamificationDashboard200ResponseDataStats = (GetGamificationDashboard200ResponseDataStats) o;
    return Objects.equals(this.level, getGamificationDashboard200ResponseDataStats.level) &&
        Objects.equals(this.totalXP, getGamificationDashboard200ResponseDataStats.totalXP) &&
        Objects.equals(this.tasksCompleted, getGamificationDashboard200ResponseDataStats.tasksCompleted) &&
        Objects.equals(this.currentStreak, getGamificationDashboard200ResponseDataStats.currentStreak) &&
        Objects.equals(this.longestStreak, getGamificationDashboard200ResponseDataStats.longestStreak) &&
        Objects.equals(this.badges, getGamificationDashboard200ResponseDataStats.badges) &&
        Objects.equals(this.nextLevel, getGamificationDashboard200ResponseDataStats.nextLevel);
  }

  @Override
  public int hashCode() {
    return Objects.hash(level, totalXP, tasksCompleted, currentStreak, longestStreak, badges, nextLevel);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetGamificationDashboard200ResponseDataStats {\n");
    sb.append("    level: ").append(toIndentedString(level)).append("\n");
    sb.append("    totalXP: ").append(toIndentedString(totalXP)).append("\n");
    sb.append("    tasksCompleted: ").append(toIndentedString(tasksCompleted)).append("\n");
    sb.append("    currentStreak: ").append(toIndentedString(currentStreak)).append("\n");
    sb.append("    longestStreak: ").append(toIndentedString(longestStreak)).append("\n");
    sb.append("    badges: ").append(toIndentedString(badges)).append("\n");
    sb.append("    nextLevel: ").append(toIndentedString(nextLevel)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("level");
    openapiFields.add("totalXP");
    openapiFields.add("tasksCompleted");
    openapiFields.add("currentStreak");
    openapiFields.add("longestStreak");
    openapiFields.add("badges");
    openapiFields.add("nextLevel");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetGamificationDashboard200ResponseDataStats
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetGamificationDashboard200ResponseDataStats.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GetGamificationDashboard200ResponseDataStats is not found in the empty JSON string", GetGamificationDashboard200ResponseDataStats.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetGamificationDashboard200ResponseDataStats.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GetGamificationDashboard200ResponseDataStats` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the optional json data is an array if present
      if (jsonObj.get("badges") != null && !jsonObj.get("badges").isJsonNull() && !jsonObj.get("badges").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `badges` to be an array in the JSON string but got `%s`", jsonObj.get("badges").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetGamificationDashboard200ResponseDataStats.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetGamificationDashboard200ResponseDataStats' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetGamificationDashboard200ResponseDataStats> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetGamificationDashboard200ResponseDataStats.class));

       return (TypeAdapter<T>) new TypeAdapter<GetGamificationDashboard200ResponseDataStats>() {
           @Override
           public void write(JsonWriter out, GetGamificationDashboard200ResponseDataStats value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetGamificationDashboard200ResponseDataStats read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetGamificationDashboard200ResponseDataStats given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetGamificationDashboard200ResponseDataStats
   * @throws IOException if the JSON string is invalid with respect to GetGamificationDashboard200ResponseDataStats
   */
  public static GetGamificationDashboard200ResponseDataStats fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetGamificationDashboard200ResponseDataStats.class);
  }

  /**
   * Convert an instance of GetGamificationDashboard200ResponseDataStats to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

