# coding: utf-8

"""
    Gamified Task Management API

    API REST gamificada para gerenciamento de tarefas com IA, XP, levels e sistema de recompensas

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.api_tasks_story_post201_response_data_quests_inner import ApiTasksStoryPost201ResponseDataQuestsInner
from openapi_client.models.api_tasks_story_post201_response_data_story import ApiTasksStoryPost201ResponseDataStory
from typing import Optional, Set
from typing_extensions import Self

class ApiTasksStoryPost201ResponseData(BaseModel):
    """
    ApiTasksStoryPost201ResponseData
    """ # noqa: E501
    story: Optional[ApiTasksStoryPost201ResponseDataStory] = None
    quests: Optional[List[ApiTasksStoryPost201ResponseDataQuestsInner]] = None
    __properties: ClassVar[List[str]] = ["story", "quests"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ApiTasksStoryPost201ResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of story
        if self.story:
            _dict['story'] = self.story.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in quests (list)
        _items = []
        if self.quests:
            for _item_quests in self.quests:
                if _item_quests:
                    _items.append(_item_quests.to_dict())
            _dict['quests'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ApiTasksStoryPost201ResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "story": ApiTasksStoryPost201ResponseDataStory.from_dict(obj["story"]) if obj.get("story") is not None else None,
            "quests": [ApiTasksStoryPost201ResponseDataQuestsInner.from_dict(_item) for _item in obj["quests"]] if obj.get("quests") is not None else None
        })
        return _obj


