# coding: utf-8

"""
    Gamified Task Management API

    API REST gamificada para gerenciamento de tarefas com IA, XP, levels e sistema de recompensas

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.get_gamification_dashboard200_response_data_stats import GetGamificationDashboard200ResponseDataStats
from openapi_client.models.get_gamification_dashboard200_response_data_user import GetGamificationDashboard200ResponseDataUser
from typing import Optional, Set
from typing_extensions import Self

class GetGamificationDashboard200ResponseData(BaseModel):
    """
    GetGamificationDashboard200ResponseData
    """ # noqa: E501
    user: Optional[GetGamificationDashboard200ResponseDataUser] = None
    stats: Optional[GetGamificationDashboard200ResponseDataStats] = None
    stories: Optional[Dict[str, Any]] = None
    recent_achievements: Optional[List[StrictStr]] = Field(default=None, alias="recentAchievements")
    active_stories: Optional[List[StrictStr]] = Field(default=None, alias="activeStories")
    __properties: ClassVar[List[str]] = ["user", "stats", "stories", "recentAchievements", "activeStories"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetGamificationDashboard200ResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of user
        if self.user:
            _dict['user'] = self.user.to_dict()
        # override the default output from pydantic by calling `to_dict()` of stats
        if self.stats:
            _dict['stats'] = self.stats.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetGamificationDashboard200ResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "user": GetGamificationDashboard200ResponseDataUser.from_dict(obj["user"]) if obj.get("user") is not None else None,
            "stats": GetGamificationDashboard200ResponseDataStats.from_dict(obj["stats"]) if obj.get("stats") is not None else None,
            "stories": obj.get("stories"),
            "recentAchievements": obj.get("recentAchievements"),
            "activeStories": obj.get("activeStories")
        })
        return _obj


