# coding: utf-8

"""
    Gamified Task Management API

    API REST gamificada para gerenciamento de tarefas com IA, XP, levels e sistema de recompensas

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.api_tasks_post_request import ApiTasksPostRequest

class TestApiTasksPostRequest(unittest.TestCase):
    """ApiTasksPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiTasksPostRequest:
        """Test ApiTasksPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiTasksPostRequest`
        """
        model = ApiTasksPostRequest()
        if include_optional:
            return ApiTasksPostRequest(
                title = 'Implementar autenticação JWT',
                description = 'Implementar sistema de autenticação usando JWT com middleware de verificação',
                status = 'pending',
                priority = 'medium',
                due_date = '2024-12-31T23:59:59Z',
                tags = ["backend","auth","jwt"]
            )
        else:
            return ApiTasksPostRequest(
                title = 'Implementar autenticação JWT',
                description = 'Implementar sistema de autenticação usando JWT com middleware de verificação',
        )
        """

    def testApiTasksPostRequest(self):
        """Test ApiTasksPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
