# coding: utf-8

"""
    Gamified Task Management API

    API REST gamificada para gerenciamento de tarefas com IA, XP, levels e sistema de recompensas

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.update_user_profile_request import UpdateUserProfileRequest

class TestUpdateUserProfileRequest(unittest.TestCase):
    """UpdateUserProfileRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateUserProfileRequest:
        """Test UpdateUserProfileRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateUserProfileRequest`
        """
        model = UpdateUserProfileRequest()
        if include_optional:
            return UpdateUserProfileRequest(
                name = 'João Silva Santos',
                email = 'joao.santos@email.com'
            )
        else:
            return UpdateUserProfileRequest(
        )
        """

    def testUpdateUserProfileRequest(self):
        """Test UpdateUserProfileRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
