# coding: utf-8

"""
    Gamified Task Management API

    API REST gamificada para gerenciamento de tarefas com IA, XP, levels e sistema de recompensas

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.api_tasks_story_post201_response_data_quests_inner import ApiTasksStoryPost201ResponseDataQuestsInner

class TestApiTasksStoryPost201ResponseDataQuestsInner(unittest.TestCase):
    """ApiTasksStoryPost201ResponseDataQuestsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiTasksStoryPost201ResponseDataQuestsInner:
        """Test ApiTasksStoryPost201ResponseDataQuestsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiTasksStoryPost201ResponseDataQuestsInner`
        """
        model = ApiTasksStoryPost201ResponseDataQuestsInner()
        if include_optional:
            return ApiTasksStoryPost201ResponseDataQuestsInner(
                quest_title = '',
                quest_description = '',
                difficulty = '',
                xp = 1.337,
                category = ''
            )
        else:
            return ApiTasksStoryPost201ResponseDataQuestsInner(
        )
        """

    def testApiTasksStoryPost201ResponseDataQuestsInner(self):
        """Test ApiTasksStoryPost201ResponseDataQuestsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
