# coding: utf-8

"""
    Gamified Task Management API

    API REST gamificada para gerenciamento de tarefas com IA, XP, levels e sistema de recompensas

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.api_gamification_badges_get200_response_data import ApiGamificationBadgesGet200ResponseData

class TestApiGamificationBadgesGet200ResponseData(unittest.TestCase):
    """ApiGamificationBadgesGet200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiGamificationBadgesGet200ResponseData:
        """Test ApiGamificationBadgesGet200ResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiGamificationBadgesGet200ResponseData`
        """
        model = ApiGamificationBadgesGet200ResponseData()
        if include_optional:
            return ApiGamificationBadgesGet200ResponseData(
                earned = [
                    openapi_client.models._api_gamification_badges_get_200_response_data_earned_inner._api_gamification_badges_get_200_response_data_earned_inner(
                        id = '', 
                        name = '', 
                        description = '', 
                        icon = '', 
                        earned = True, )
                    ],
                available = [
                    None
                    ],
                total = 1.337,
                earned_count = 1.337
            )
        else:
            return ApiGamificationBadgesGet200ResponseData(
        )
        """

    def testApiGamificationBadgesGet200ResponseData(self):
        """Test ApiGamificationBadgesGet200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
