# coding: utf-8

"""
    Gamified Task Management API

    API REST gamificada para gerenciamento de tarefas com IA, XP, levels e sistema de recompensas

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.api_tasks_stats_get200_response_data_stats import ApiTasksStatsGet200ResponseDataStats

class TestApiTasksStatsGet200ResponseDataStats(unittest.TestCase):
    """ApiTasksStatsGet200ResponseDataStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiTasksStatsGet200ResponseDataStats:
        """Test ApiTasksStatsGet200ResponseDataStats
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiTasksStatsGet200ResponseDataStats`
        """
        model = ApiTasksStatsGet200ResponseDataStats()
        if include_optional:
            return ApiTasksStatsGet200ResponseDataStats(
                total = 25,
                pending = 10,
                in_progress = 8,
                completed = 7,
                overdue = 3,
                completed_this_month = 5
            )
        else:
            return ApiTasksStatsGet200ResponseDataStats(
        )
        """

    def testApiTasksStatsGet200ResponseDataStats(self):
        """Test ApiTasksStatsGet200ResponseDataStats"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
