# coding: utf-8

"""
    Gamified Task Management API

    API REST gamificada para gerenciamento de tarefas com IA, XP, levels e sistema de recompensas

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.api_tasks_status_status_get200_response_data import ApiTasksStatusStatusGet200ResponseData

class TestApiTasksStatusStatusGet200ResponseData(unittest.TestCase):
    """ApiTasksStatusStatusGet200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiTasksStatusStatusGet200ResponseData:
        """Test ApiTasksStatusStatusGet200ResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiTasksStatusStatusGet200ResponseData`
        """
        model = ApiTasksStatusStatusGet200ResponseData()
        if include_optional:
            return ApiTasksStatusStatusGet200ResponseData(
                tasks = [
                    openapi_client.models.task.Task(
                        id = '64a1b2c3d4e5f6789abcdef1', 
                        title = 'Implementar Story-Mode', 
                        status = 'pending', 
                        priority = 'low', 
                        user_id = '64a1b2c3d4e5f6789abcdef0', )
                    ],
                pagination = openapi_client.models._api_tasks_status__status__get_200_response_data_pagination._api_tasks_status__status__get_200_response_data_pagination(
                    current = 56, 
                    pages = 56, 
                    total = 56, 
                    limit = 56, )
            )
        else:
            return ApiTasksStatusStatusGet200ResponseData(
        )
        """

    def testApiTasksStatusStatusGet200ResponseData(self):
        """Test ApiTasksStatusStatusGet200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
