/**
 * Gamified Task Management API
 * API REST gamificada para gerenciamento de tarefas com IA, XP, levels e sistema de recompensas
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GamifiedTaskManagementApi);
  }
}(this, function(expect, GamifiedTaskManagementApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GamifiedTaskManagementApi.GetLeaderboard200ResponseDataLeaderboardInner();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GetLeaderboard200ResponseDataLeaderboardInner', function() {
    it('should create an instance of GetLeaderboard200ResponseDataLeaderboardInner', function() {
      // uncomment below and update the code to test GetLeaderboard200ResponseDataLeaderboardInner
      //var instance = new GamifiedTaskManagementApi.GetLeaderboard200ResponseDataLeaderboardInner();
      //expect(instance).to.be.a(GamifiedTaskManagementApi.GetLeaderboard200ResponseDataLeaderboardInner);
    });

    it('should have the property rank (base name: "rank")', function() {
      // uncomment below and update the code to test the property rank
      //var instance = new GamifiedTaskManagementApi.GetLeaderboard200ResponseDataLeaderboardInner();
      //expect(instance).to.be();
    });

    it('should have the property username (base name: "username")', function() {
      // uncomment below and update the code to test the property username
      //var instance = new GamifiedTaskManagementApi.GetLeaderboard200ResponseDataLeaderboardInner();
      //expect(instance).to.be();
    });

    it('should have the property level (base name: "level")', function() {
      // uncomment below and update the code to test the property level
      //var instance = new GamifiedTaskManagementApi.GetLeaderboard200ResponseDataLeaderboardInner();
      //expect(instance).to.be();
    });

    it('should have the property totalXP (base name: "totalXP")', function() {
      // uncomment below and update the code to test the property totalXP
      //var instance = new GamifiedTaskManagementApi.GetLeaderboard200ResponseDataLeaderboardInner();
      //expect(instance).to.be();
    });

    it('should have the property tasksCompleted (base name: "tasksCompleted")', function() {
      // uncomment below and update the code to test the property tasksCompleted
      //var instance = new GamifiedTaskManagementApi.GetLeaderboard200ResponseDataLeaderboardInner();
      //expect(instance).to.be();
    });

    it('should have the property currentStreak (base name: "currentStreak")', function() {
      // uncomment below and update the code to test the property currentStreak
      //var instance = new GamifiedTaskManagementApi.GetLeaderboard200ResponseDataLeaderboardInner();
      //expect(instance).to.be();
    });

    it('should have the property badges (base name: "badges")', function() {
      // uncomment below and update the code to test the property badges
      //var instance = new GamifiedTaskManagementApi.GetLeaderboard200ResponseDataLeaderboardInner();
      //expect(instance).to.be();
    });

  });

}));
