/**
 * Gamified Task Management API
 * API REST gamificada para gerenciamento de tarefas com IA, XP, levels e sistema de recompensas
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApiTasksStoryPost201ResponseDataQuestsInner model module.
 * @module model/ApiTasksStoryPost201ResponseDataQuestsInner
 * @version 1.0.0
 */
class ApiTasksStoryPost201ResponseDataQuestsInner {
    /**
     * Constructs a new <code>ApiTasksStoryPost201ResponseDataQuestsInner</code>.
     * @alias module:model/ApiTasksStoryPost201ResponseDataQuestsInner
     */
    constructor() { 
        
        ApiTasksStoryPost201ResponseDataQuestsInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ApiTasksStoryPost201ResponseDataQuestsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiTasksStoryPost201ResponseDataQuestsInner} obj Optional instance to populate.
     * @return {module:model/ApiTasksStoryPost201ResponseDataQuestsInner} The populated <code>ApiTasksStoryPost201ResponseDataQuestsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiTasksStoryPost201ResponseDataQuestsInner();

            if (data.hasOwnProperty('questTitle')) {
                obj['questTitle'] = ApiClient.convertToType(data['questTitle'], 'String');
            }
            if (data.hasOwnProperty('questDescription')) {
                obj['questDescription'] = ApiClient.convertToType(data['questDescription'], 'String');
            }
            if (data.hasOwnProperty('difficulty')) {
                obj['difficulty'] = ApiClient.convertToType(data['difficulty'], 'String');
            }
            if (data.hasOwnProperty('xp')) {
                obj['xp'] = ApiClient.convertToType(data['xp'], 'Number');
            }
            if (data.hasOwnProperty('category')) {
                obj['category'] = ApiClient.convertToType(data['category'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiTasksStoryPost201ResponseDataQuestsInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiTasksStoryPost201ResponseDataQuestsInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['questTitle'] && !(typeof data['questTitle'] === 'string' || data['questTitle'] instanceof String)) {
            throw new Error("Expected the field `questTitle` to be a primitive type in the JSON string but got " + data['questTitle']);
        }
        // ensure the json data is a string
        if (data['questDescription'] && !(typeof data['questDescription'] === 'string' || data['questDescription'] instanceof String)) {
            throw new Error("Expected the field `questDescription` to be a primitive type in the JSON string but got " + data['questDescription']);
        }
        // ensure the json data is a string
        if (data['difficulty'] && !(typeof data['difficulty'] === 'string' || data['difficulty'] instanceof String)) {
            throw new Error("Expected the field `difficulty` to be a primitive type in the JSON string but got " + data['difficulty']);
        }
        // ensure the json data is a string
        if (data['category'] && !(typeof data['category'] === 'string' || data['category'] instanceof String)) {
            throw new Error("Expected the field `category` to be a primitive type in the JSON string but got " + data['category']);
        }

        return true;
    }


}



/**
 * @member {String} questTitle
 */
ApiTasksStoryPost201ResponseDataQuestsInner.prototype['questTitle'] = undefined;

/**
 * @member {String} questDescription
 */
ApiTasksStoryPost201ResponseDataQuestsInner.prototype['questDescription'] = undefined;

/**
 * @member {String} difficulty
 */
ApiTasksStoryPost201ResponseDataQuestsInner.prototype['difficulty'] = undefined;

/**
 * @member {Number} xp
 */
ApiTasksStoryPost201ResponseDataQuestsInner.prototype['xp'] = undefined;

/**
 * @member {String} category
 */
ApiTasksStoryPost201ResponseDataQuestsInner.prototype['category'] = undefined;






export default ApiTasksStoryPost201ResponseDataQuestsInner;

