//
// GetUserById200ResponseDataTaskStats.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetUserById200ResponseDataTaskStats: Codable, JSONEncodable, Hashable {

    public var total: Int?
    public var pending: Int?
    public var inProgress: Int?
    public var completed: Int?

    public init(total: Int? = nil, pending: Int? = nil, inProgress: Int? = nil, completed: Int? = nil) {
        self.total = total
        self.pending = pending
        self.inProgress = inProgress
        self.completed = completed
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case total
        case pending
        case inProgress = "in_progress"
        case completed
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(total, forKey: .total)
        try container.encodeIfPresent(pending, forKey: .pending)
        try container.encodeIfPresent(inProgress, forKey: .inProgress)
        try container.encodeIfPresent(completed, forKey: .completed)
    }
}

