//
// GetUserStats200ResponseDataMostActiveUsersInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetUserStats200ResponseDataMostActiveUsersInner: Codable, JSONEncodable, Hashable {

    public var userId: String?
    public var name: String?
    public var email: String?
    public var taskCount: Int?

    public init(userId: String? = nil, name: String? = nil, email: String? = nil, taskCount: Int? = nil) {
        self.userId = userId
        self.name = name
        self.email = email
        self.taskCount = taskCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userId
        case name
        case email
        case taskCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(userId, forKey: .userId)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(taskCount, forKey: .taskCount)
    }
}

