//
// ProcessShareWebhookRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ProcessShareWebhookRequest: Codable, JSONEncodable, Hashable {

    public var eventType: String?
    public var userId: String?
    public var data: AnyCodable?

    public init(eventType: String? = nil, userId: String? = nil, data: AnyCodable? = nil) {
        self.eventType = eventType
        self.userId = userId
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case eventType = "event_type"
        case userId = "user_id"
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(eventType, forKey: .eventType)
        try container.encodeIfPresent(userId, forKey: .userId)
        try container.encodeIfPresent(data, forKey: .data)
    }
}

