//
// UserGamification.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserGamification: Codable, JSONEncodable, Hashable {

    public var level: Double?
    public var totalXP: Double?

    public init(level: Double? = nil, totalXP: Double? = nil) {
        self.level = level
        self.totalXP = totalXP
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case level
        case totalXP
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(level, forKey: .level)
        try container.encodeIfPresent(totalXP, forKey: .totalXP)
    }
}

