/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.CompleteQuestRequest

class CompleteQuestRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CompleteQuestRequest
        //val modelInstance = CompleteQuestRequest()

        // to test the property `completionTime` - Tempo gasto em minutos
        should("test completionTime") {
            // uncomment below to test the property
            //modelInstance.completionTime shouldBe ("TODO")
        }

    }
}
