/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.CreateStoryFromTasksRequest
import org.openapitools.client.models.CreateStoryFromTasksRequestUserPreferences

class CreateStoryFromTasksRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreateStoryFromTasksRequest
        //val modelInstance = CreateStoryFromTasksRequest()

        // to test the property `taskIds`
        should("test taskIds") {
            // uncomment below to test the property
            //modelInstance.taskIds shouldBe ("TODO")
        }

        // to test the property `userPreferences`
        should("test userPreferences") {
            // uncomment below to test the property
            //modelInstance.userPreferences shouldBe ("TODO")
        }

    }
}
