/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetTaskStats200ResponseDataStats

class GetTaskStats200ResponseDataStatsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetTaskStats200ResponseDataStats
        //val modelInstance = GetTaskStats200ResponseDataStats()

        // to test the property `total`
        should("test total") {
            // uncomment below to test the property
            //modelInstance.total shouldBe ("TODO")
        }

        // to test the property `pending`
        should("test pending") {
            // uncomment below to test the property
            //modelInstance.pending shouldBe ("TODO")
        }

        // to test the property `inProgress`
        should("test inProgress") {
            // uncomment below to test the property
            //modelInstance.inProgress shouldBe ("TODO")
        }

        // to test the property `completed`
        should("test completed") {
            // uncomment below to test the property
            //modelInstance.completed shouldBe ("TODO")
        }

        // to test the property `overdue`
        should("test overdue") {
            // uncomment below to test the property
            //modelInstance.overdue shouldBe ("TODO")
        }

        // to test the property `completedThisMonth`
        should("test completedThisMonth") {
            // uncomment below to test the property
            //modelInstance.completedThisMonth shouldBe ("TODO")
        }

    }
}
