/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetUserById200ResponseData
import org.openapitools.client.models.GetUserById200ResponseDataTaskStats
import org.openapitools.client.models.User

class GetUserById200ResponseDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetUserById200ResponseData
        //val modelInstance = GetUserById200ResponseData()

        // to test the property `user`
        should("test user") {
            // uncomment below to test the property
            //modelInstance.user shouldBe ("TODO")
        }

        // to test the property `taskStats`
        should("test taskStats") {
            // uncomment below to test the property
            //modelInstance.taskStats shouldBe ("TODO")
        }

    }
}
