/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetUserStats200ResponseData
import org.openapitools.client.models.GetUserStats200ResponseDataMostActiveUsersInner
import org.openapitools.client.models.GetUserStats200ResponseDataTasks
import org.openapitools.client.models.GetUserStats200ResponseDataUsers

class GetUserStats200ResponseDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetUserStats200ResponseData
        //val modelInstance = GetUserStats200ResponseData()

        // to test the property `users`
        should("test users") {
            // uncomment below to test the property
            //modelInstance.users shouldBe ("TODO")
        }

        // to test the property `tasks`
        should("test tasks") {
            // uncomment below to test the property
            //modelInstance.tasks shouldBe ("TODO")
        }

        // to test the property `mostActiveUsers`
        should("test mostActiveUsers") {
            // uncomment below to test the property
            //modelInstance.mostActiveUsers shouldBe ("TODO")
        }

    }
}
