/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ListTasksByStatus200ResponseData
import org.openapitools.client.models.ListTasksByStatus200ResponseDataPagination
import org.openapitools.client.models.Task

class ListTasksByStatus200ResponseDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ListTasksByStatus200ResponseData
        //val modelInstance = ListTasksByStatus200ResponseData()

        // to test the property `tasks`
        should("test tasks") {
            // uncomment below to test the property
            //modelInstance.tasks shouldBe ("TODO")
        }

        // to test the property `pagination`
        should("test pagination") {
            // uncomment below to test the property
            //modelInstance.pagination shouldBe ("TODO")
        }

    }
}
